services:
  ovms:
    command: >
      --source_model OpenVINO/gemma-4-31B-it-int4-ov
      --model_name gemma-4-31b
      --model_repository_path /models
      --task text_generation
      --target_device GPU
      --rest_port 8000
      --max_num_batched_tokens 32768
      --cache_size 24
    container_name: ovms
    devices:
      - /dev/dri:/dev/dri
    environment:
      HF_TOKEN: ${HF_TOKEN}
    group_add:
      - '993'
    image: openvino/model_server:2026.2-gpu@sha256:fdc34725b35d79cde23cff1967f90efb40237b7cf5545a70460209056f3da733
    restart: always
    shm_size: 16gb
    volumes:
      - ovms-models:/models

  db:
    container_name: open-webui-db
    image: pgvector/pgvector:0.8.2-pg18-trixie@sha256:b7337db8fe39d12fe8ecb0003c72680f24479813a744b43154eee6f2eab5a5f3
    environment:
      POSTGRES_USER: webui
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: openwebui
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql

  open-webui:
    container_name: open-webui
    depends_on:
      - ovms
      - db
    environment:
      DATABASE_URL: postgresql://webui:${DB_PASSWORD}@db:5432/openwebui
      ENABLE_SIGNUP: ${ENABLE_SIGNUP:-False}
      HF_TOKEN: ${HF_TOKEN}
      PGVECTOR_DB_URL: postgresql://webui:${DB_PASSWORD}@db:5432/openwebui
      VECTOR_DB: pgvector
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY:-}
    image: ghcr.io/open-webui/open-webui:v0.9.5@sha256:e045bde3b004cc7f8c319412345eb56c87ea6ac57031534a31ca37ad5424beb3
    networks:
      - default
      - stzky-ingress
    restart: always
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  ovms-models:
  pg-data:
  open-webui-data:

networks:
  stzky-ingress:
    external: true
