services:
  alloy:
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    container_name: alloy
    environment:
      ALLOY_PROMETHEUS_PASSWORD: ${ALLOY_PROMETHEUS_PASSWORD}
      ALLOY_PROMETHEUS_USERNAME: ${ALLOY_PROMETHEUS_USERNAME}
    image: grafana/alloy:v1.16.3@sha256:84b76d56c5943025515438fd45cbb5995386a0260d072c9b671dfd7f539f9c01
    networks:
      - default
      - stzky-ingress
    restart: always
    user: '0'
    volumes:
      - ./config/alloy:/etc/alloy:ro
      - alloy_data:/var/lib/alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro

  cadvisor:
    container_name: cadvisor
    devices:
      - /dev/kmsg:/dev/kmsg
    image: ghcr.io/google/cadvisor:0.57.0@sha256:e75bdb03b74b0b6995f208f166fead2e6e555dde73e44200113bb26f41b1981d
    privileged: true
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  database:
    container_name: grafana_postgres
    environment:
      POSTGRES_DB: ${GF_DATABASE_NAME}
      POSTGRES_PASSWORD: ${GF_DATABASE_PASSWORD}
      POSTGRES_USER: ${GF_DATABASE_USER}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    image: postgres:17.10-bookworm@sha256:517f51201e18a12503a42945ef0b434d65a5297d72a4180f11905d905fcc5612
    restart: always
    volumes:
      - /opt/grafana/postgres:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_DATABASE_HOST: ${GF_DATABASE_HOST}
      GF_DATABASE_NAME: ${GF_DATABASE_NAME}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
      GF_DATABASE_TYPE: ${GF_DATABASE_TYPE}
      GF_DATABASE_USER: ${GF_DATABASE_USER}
      GF_REMOTE_CACHE_CONNSTR: ${GF_REMOTE_CACHE_CONNSTR}
      GF_REMOTE_CACHE_TYPE: redis
      GF_SECURITY_COOKIE_SECURE: true
      GF_SECURITY_COOKIE_SAMESITE: Strict
      GF_SECURITY_CONTENT_SECURITY_POLICY: true
      GF_SERVER_DOMAIN: graph.stzky.com
      GF_SERVER_ROOT_URL: https://graph.stzky.com
      GF_SERVER_ENABLE_GZIP: false
      GF_SMTP_ENABLED: true
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS}
      GF_SMTP_FROM_NAME: ${GF_SMTP_FROM_NAME}
      GF_SMTP_HOST: ${GF_SMTP_HOST}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD}
      GF_SMTP_USER: ${GF_SMTP_FROM_NAME}
      GF_SNAPSHOTS_EXTERNAL_ENABLED: false
      GF_USERS_DEFAULT_THEME: system
    image: grafana/grafana:13.0.2@sha256:5dad0df181cb644a14e13617b913b261a54f7d4fd4510721dba420929f35bea2
    networks:
      - default
      - stzky-ingress
    restart: always
    user: '0'
    volumes:
      - /opt/grafana/grafana:/var/lib/grafana

  loki:
    command: -config.file=/etc/loki/local-config.yaml
    container_name: loki
    image: grafana/loki:3.7.2@sha256:191d4fdfb7264f16989f0a57f320872620a5a7c2ceeec6229212c4190ec49b86
    networks:
      - default
      - stzky-ingress
    restart: always
    volumes:
      - ./config/loki:/etc/loki:ro
      - loki_data:/loki

  node-exporter:
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    container_name: node_exporter
    image: prom/node-exporter:v1.11.1@sha256:e9cff4fc67b1818f8c97adb115b9f12c9a54b533de86765d4a0effc01b357205
    pid: host
    restart: always
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=60d
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    container_name: prometheus
    image: prom/prometheus:v3.12.0@sha256:69f5241418838263316593f7274a304b095c40bcf22e57272865da91bd60a8ac
    networks:
      - default
      - stzky-ingress
    restart: always
    volumes:
      - ./config/prometheus:/etc/prometheus:ro
      - /opt/grafana/prometheus:/prometheus

  redis:
    container_name: grafana_redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    image: valkey/valkey:8.1.3-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    restart: always
    volumes:
      - /opt/grafana/redis:/data

  snmp-exporter:
    container_name: snmp_exporter
    image: prom/snmp-exporter:v0.30.1@sha256:e5fd5e8b43ace6c088fe9bf0b37b7fff0e04380bee352be7ec41b853a4dd5859
    restart: always

networks:
  stzky-ingress:
    external: true

volumes:
  alloy_data:
  loki_data:
