services:
  caddy:
    build: .
    cap_add:
      - NET_ADMIN
    container_name: caddy
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - MCP_ACCESS_TOKEN=${MCP_ACCESS_TOKEN}
      - PROMETHEUS_HASHED_PASSWORD=${PROMETHEUS_HASHED_PASSWORD}
      - PROMETHEUS_AUTH_USERNAME=${ALLOY_PROMETHEUS_USERNAME}
    image: ghcr.io/ykzts/caddy
    networks:
      - stzky-ingress
    ports:
      - 443:443
      - 443:443/udp
      - 80:80
    restart: always
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./config/caddy:/etc/caddy:ro
      - ./public:/var/www/html:ro

volumes:
  caddy_config:
  caddy_data:

networks:
  stzky-ingress:
    external: true
