image:
  repository: ghcr.io/louislam/uptime-kuma
  tag: "2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e"

database:
  image:
    repository: mariadb
    tag: "12.2.2-noble@sha256:350261292d0129fd4b24f537dcf05ecd3ebe34d39d5b592af551f38310e7a167"
  name: uptime_kuma
  user: uptime_kuma
  password: changeme

service: {}

ingress:
  enabled: true
  hostnames:
    - uptime.stzky.com
    - status.stzky.com
    - status.ykzts.com
    - status.ykzts.technology
  gateway:
    name: gateway
    namespace: grafana
