services:
  roonserver:
    container_name: roonserver
    environment:
      ROON_INSTALL_BRANCH: production
    image: ghcr.io/roonlabs/roonserver:1.0.7@sha256:8deef4b11e04b869b0f33d1a216f27a0cd83106f1548a4dc3c666300f3be4652
    network_mode: host
    restart: always
    volumes:
      - roon-data:/Roon
      - ${ROON_SERVER_MUSIC_DIR}:/Music
      - ${ROON_SERVER_BACKUP_DIR}:/RoonBackups

  alloy:
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    container_name: roonserver_alloy
    image: grafana/alloy:v1.18.0@sha256:491b0578c04983fd54fe99b587b6fab4404dc46d0dc16677bd6b00cc1140b308
    networks:
      - stzky-ingress
    restart: always
    user: '0'
    volumes:
      - roon-data:/Roon:ro
      - ./config/alloy:/etc/alloy:ro

volumes:
  roon-data:

networks:
  stzky-ingress:
    external: true
