name: epub-web

services:
  epub-web:
    container_name: epub-web
    platform: linux/amd64
    environment:
      EPUB_WEB_MAX_UPLOAD_SIZE: 256
      EPUB_WEB_MAX_PAGES: 500
      EPUB_WEB_WORKERS: 8
      EPUB_WEB_REQUEST_TIMEOUT: 90s
      EPUB_WEB_SHUTDOWN_TIMEOUT: 15s
    image: ghcr.io/publira/epub-web:1.2.6@sha256:2e632a3f3bcaca40bba5a6e89a4b95b614060da5ad192e79216c7a0e54ba03d7
    networks:
      - default
      - stzky-ingress
    restart: always

networks:
  stzky-ingress:
    external: true
