name: epub-web

services:
  epub-web:
    container_name: epub-web
    platform: linux/amd64
    environment:
      EPUB_WEB_MAX_UPLOAD_SIZE: 256
      EPUB_WEB_MAX_PAGES: 500
      EPUB_WEB_WORKERS: 8
      EPUB_WEB_REQUEST_TIMEOUT: 90s
      EPUB_WEB_SHUTDOWN_TIMEOUT: 15s
    image: ghcr.io/publira/epub-web:1.2.3@sha256:94837bde91c4cca1902733d1cb4f08e1bd871da4066874c8c2317ee2e5f7fe62
    networks:
      - default
      - stzky-ingress
    restart: always

networks:
  stzky-ingress:
    external: true
