services:
  n8n:
    container_name: n8n
    depends_on:
      n8n-db:
        condition: service_healthy
    image: docker.n8n.io/n8nio/n8n:2.21.7
    environment:
      DB_POSTGRESDB_HOST: n8n-db
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD:-n8n}
      DB_POSTGRESDB_PORT: '5432'
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-n8n}
      DB_TYPE: postgresdb
      GENERIC_TIMEZONE: Asia/Tokyo
      N8N_HOST: flow.stzky.com
      N8N_PROTOCOL: https
    networks:
      - default
      - stzky-ingress
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n

  n8n-db:
    container_name: n8n_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8n}
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
    healthcheck:
      interval: 10s
      retries: 5
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      timeout: 5s
    image: postgres:18.4-alpine3.23@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  n8n_data:
  pg_data:

networks:
  stzky-ingress:
    external: true
