services:
  database:
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}', '-d', '${DB_DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
  immich-machine-learning:
    profiles:
      - donotstart
