services:
  database:
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  immich-machine-learning:
    profiles:
      - donotstart
