name: epub-web

services:
  epub-web:
    container_name: epub-web
    platform: linux/amd64
    environment:
      EPUB_WEB_MAX_UPLOAD_SIZE: 256
      EPUB_WEB_MAX_PAGES: 500
      EPUB_WEB_WORKERS: 8
      EPUB_WEB_REQUEST_TIMEOUT: 90s
      EPUB_WEB_SHUTDOWN_TIMEOUT: 15s
    image: ghcr.io/publira/epub-web:1.1.4@sha256:617baa62bdb9b5d66ea45da2a8ec9ea51f363d464c4692803aa598728a18eaec
    networks:
      - default
      - stzky-ingress
    restart: always

networks:
  stzky-ingress:
    external: true
