---
- Daily Check-ins:
    - Genshin Impact:
        - abbr: GI
          href: https://act.hoyolab.com/ys/event/signin-sea-v3/index.html?act_id=e202102251931481

    - "Honkai: Star Rail":
        - abbr: SR
          href: https://act.hoyolab.com/bbs/event/signin/hkrpg/index.html?act_id=e202303301540311

    - Zenless Zone Zero:
        - abbr: ZZ
          href: https://act.hoyolab.com/bbs/event/signin/zzz/e202406031448091.html?act_id=e202406031448091

    - "Arknights: Endfield":
        - abbr: AE
          href: https://game.skport.com/endfield/sign-in

- AI Chat:
    - Gemini:
        - abbr: GM
          href: https://gemini.google.com/app

    - Grok:
        - abbr: GK
          href: https://grok.com/
