services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      KUBECONFIG: /k8s/kubeconfig.yaml
    network_mode: service:k3s
    volumes:
      - ../..:/workspaces:cached
      - k3s-kubeconfig:/k8s:ro

  k3s:
    command: server --disable=traefik --disable-kube-proxy --flannel-backend=none --disable-network-policy --tls-san 127.0.0.1
    environment:
      K3S_KUBECONFIG_OUTPUT: /k8s/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: "666"
    image: rancher/k3s:v1.36.0-k3s1@sha256:38069dc4a22a056f427f4f37c887303697cc817f7735e57dd142e169af7f398f
    privileged: true
    volumes:
      - k3s-kubeconfig:/k8s
      - type: bind
        source: /sys/fs/bpf
        target: /sys/fs/bpf
        bind:
          propagation: shared
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        bind:
          propagation: shared

volumes:
  k3s-kubeconfig:
