services:
  homepage:
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: stzky.com
      LOG_TARGETS: stdout
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 20s
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://127.0.0.1:3000/api/healthcheck']
      timeout: 3s
    image: ghcr.io/gethomepage/homepage:v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    networks:
      - default
      - stzky-ingress
    restart: always
    volumes:
      - ./config/homepage:/app/config:ro
      - ./public/images:/app/public/images:ro

networks:
  stzky-ingress:
    external: true
