name: uptime-kuma

services:
  database:
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: ${MYSQL_USER}
    image: mariadb:12.2.2-noble@sha256:350261292d0129fd4b24f537dcf05ecd3ebe34d39d5b592af551f38310e7a167
    restart: always
    volumes:
      - /opt/uptime-kuma/mariadb:/var/lib/mysql

  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      database:
        condition: service_started
    environment:
      UPTIME_KUMA_DB_HOSTNAME: database
      UPTIME_KUMA_DB_NAME: ${MYSQL_DATABASE}
      UPTIME_KUMA_DB_PASSWORD: ${MYSQL_PASSWORD}
      UPTIME_KUMA_DB_PORT: 3306
      UPTIME_KUMA_DB_TYPE: mariadb
      UPTIME_KUMA_DB_USERNAME: ${MYSQL_USER}
    image: ghcr.io/louislam/uptime-kuma:2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
    networks:
      - default
      - stzky-ingress
    restart: always

networks:
  stzky-ingress:
    external: true
